# Generated by Django 2.0 on 2018-01-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('base_info', models.TextField()),
                ('career', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('award', models.TextField(blank=True)),
                ('language', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
        ),
    ]
