# Generated by Django 2.0 on 2018-02-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='achivement',
            new_name='achievement',
        ),
    ]
