# Generated by Django 2.0 on 2018-01-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('since', models.DateField()),
                ('until', models.DateField(blank=True)),
                ('currently_employed', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='career',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='language',
        ),
        migrations.AddField(
            model_name='career',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
