# Generated by Django 2.0 on 2018-02-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20180208_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='email',
        ),
    ]
