# Generated by Django 2.0 on 2018-01-31 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20180130_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Eduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('research_content', models.TextField()),
                ('since', models.DateField()),
                ('until', models.DateField(blank=True)),
                ('currently_attending', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('github', models.CharField(max_length=50)),
                ('stackoverflow', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('google_plus', models.CharField(max_length=50)),
                ('blog', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='award',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='link',
        ),
        migrations.AddField(
            model_name='career',
            name='achivement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='eduction',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='award',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
